### ISSUE TITLE
Descriptions of surveys

### ISSUE THREAD

**Issue by rosehartman** [InteragencyEcologicalProgram/zooper#1]
Somewhere in the documentation we might want to have a little more info about the datasets we are combining. Mostly we can cite the metadata report, but we want to make sure we give credit to the agencies collecting the data when we distribute the package.

**Comment by sbashevkin** [comment]
Hmm apparently linking to an issue in a commit automatically closes the issue. Anyway, I added short descriptions of the surveys to the `?zooper` documentation. Feel free to edit R/zooper.R and submit a PR if you want to make any edits to my descriptions.
